import './globals.css'
import Header from "@/app/components/Header/Header";
import styles from './layout.module.scss'
import {FaRegEnvelope, FaTelegramPlane} from "react-icons/fa";

export const metadata = {
    title: 'SKpro - Портфолио',
    description: 'Generated by create next app',
}

const Layout = ({
                    children,
                }: {
    children: React.ReactNode
}) => {
    return (
        <html lang="en">
        <body className={styles.layout}>
        <Header/>
        <div className={styles.content}>
            <div className={styles.sidebar}>
                <FaTelegramPlane/>
                <FaRegEnvelope/>
            </div>
            {children}
        </div>
        </body>
        </html>
    )
}

export default Layout
